namespace RedCell.Devices.LedDisplay.Daktronics
{
    internal enum CommandsV1
    {
        Unsupported = 0x00,
        SetConfiguration = 0x01,
        GetStatus = 0x02,
        SendFileBlock = 0x03,
        ReceiveFileBlock = 0x04,
        SendMessage = 0x05,
        RunMessage = 0x06,
        StopMessage = 0x07,
        RetrieveMessage = 0x08,
        RetrieveMessageList = 0x09,
        RemoveMessage = 0x0A,
        SendSchedule = 0x0B,
        RunSchedule = 0x0C,
        StopSchedule = 0x0D,
        SetDimming = 0x0E,
        BlankSign = 0x0F,
        SetTime = 0x10,
        TestPattern = 0x11,
        ResetSign = 0x12,
        DownloadCode = 0x13,
        DownloadFont = 0x14,
        SetCounter = 0x15,
        SendRTD = 0x16,
        SetDefaultMessage = 0x17,
        SetSerialNumber = 0x18,
        EraseFirmware = 0x19,
        SendGraphic = 0x1A,
        RetrieveGraphicList = 0x1B,
        AddToSchedule = 0x1C,
        ChangePassword = 0x1D,
        RemoveGraphic = 0x1E,
        SetSoftwareAddress = 0x1F,
        SetTemperatureOffset = 0x20,
        SetDataViewOffset = 0x21,
        SetLineFrequencyMode = 0x22,
        StartCounter = 0x23,
        StopCounter = 0x24,
        RetrieveGraphic = 0x25,
    };
}
